version: "3.3"
services:
  deconz:
    container_name: deconz
    image: marthoc/deconz
    network_mode: host
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/MediaCube/deconz/config:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_DEVICE=/dev/ttyACM0
